# Generated by Django 3.2.16 on 2025-12-15 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20251215_1636'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='pub_date',
        ),
        migrations.RemoveField(
            model_name='post',
            name='created_at',
        ),
    ]
